export const OTD_ANCHORS = [
  {
    "date_mmdd": "01-01",
    "year": 1974,
    "color": "var(--blue)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "DiGregorio dishes 25 assists — a rookie record that still stands",
    "detail": "Ernie DiGregorio of the Buffalo Braves handed out 25 assists in a 120-119 win over the Portland Trail Blazers on New Year's Day 1974, setting a single-game record for assists by a rookie that has never been broken.",
    "statChip": { "cls": "up", "text": "25 AST" },
    "players": ["Ernie DiGregorio"]
  },
  {
    "date_mmdd": "01-10",
    "year": 1986,
    "color": "var(--amber)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "Kareem hits 34,000 career points — the only man ever to do it",
    "detail": "Kareem Abdul-Jabbar of the Los Angeles Lakers scored his 34,000th career point on January 10, 1986, becoming the only NBA player in history to reach that milestone. He would finish with 38,387 — a record that stood 39 years.",
    "statChip": { "cls": "up", "text": "34,000 PTS" },
    "players": ["Kareem Abdul-Jabbar"]
  },
  {
    "date_mmdd": "01-22",
    "year": 2006,
    "color": "var(--lime)",
    "tag": "RECORD",
    "tagIcon": "flame",
    "headline": "Kobe drops 81. The second-highest single-game score in NBA history.",
    "detail": "Kobe Bryant scored 81 points for the Los Angeles Lakers against the Toronto Raptors on January 22, 2006, in a 122-104 win. He scored 55 of those in the second half. Only Wilt Chamberlain's 100-point game ranks higher in NBA history.",
    "statChip": { "cls": "up", "text": "81 PTS" },
    "players": ["Kobe Bryant"]
  },
  {
    "date_mmdd": "01-23",
    "year": 2015,
    "color": "var(--lime)",
    "tag": "RECORD",
    "tagIcon": "zap",
    "headline": "Klay Thompson scores 37 points in a single quarter",
    "detail": "Klay Thompson of the Golden State Warriors scored 37 points in the third quarter alone against the Sacramento Kings on January 23, 2015, setting an NBA record for most points in a single quarter. He finished with 52 points in the game.",
    "statChip": { "cls": "up", "text": "37 PTS/QTR" },
    "players": ["Klay Thompson"]
  },
  {
    "date_mmdd": "01-31",
    "year": 2018,
    "color": "var(--coral)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Harden becomes the first player ever with a 60-point triple-double",
    "detail": "James Harden of the Houston Rockets scored 60 points with 10 rebounds and 11 assists against the Orlando Magic on January 31, 2018, in a 114-107 win. No player in NBA history had ever combined 60 points with a triple-double in the same game.",
    "statChip": { "cls": "up", "text": "60 PTS" },
    "players": ["James Harden"]
  },
  {
    "date_mmdd": "02-01",
    "year": 1984,
    "color": "var(--amber)",
    "tag": "RECORD",
    "tagIcon": "flame",
    "headline": "Bernard King scores 50 points two nights in a row",
    "detail": "Bernard King of the New York Knicks scored 50 points at Dallas on February 1, 1984, one night after dropping 50 in San Antonio. He became the first player to score 50 on consecutive nights since Wilt Chamberlain did it 20 years earlier.",
    "statChip": { "cls": "up", "text": "50-50 PTS" },
    "players": ["Bernard King"]
  },
  {
    "date_mmdd": "02-01",
    "year": 1995,
    "color": "var(--blue)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "Stockton becomes the NBA's all-time assists leader",
    "detail": "John Stockton of the Utah Jazz surpassed Magic Johnson's all-time assists record with a bounce pass to Karl Malone — who hit the corner jumper — during a 129-88 win over Denver on February 1, 1995. Stockton finished the game with 16 assists.",
    "statChip": { "cls": "up", "text": "9,922 AST" },
    "players": ["John Stockton"]
  },
  {
    "date_mmdd": "02-07",
    "year": 1987,
    "color": "var(--lime)",
    "tag": "RECORD",
    "tagIcon": "flame",
    "headline": "Tom Chambers becomes the first player to win All-Star MVP on the road",
    "detail": "Tom Chambers of the Seattle SuperSonics scored 34 points in the 1987 NBA All-Star Game in Seattle, becoming the first player to win All-Star Game MVP while playing in his home arena's rival city. The West defeated the East 154-149 in overtime.",
    "statChip": { "cls": "up", "text": "34 PTS" },
    "players": ["Tom Chambers"]
  },
  {
    "date_mmdd": "02-27",
    "year": 1990,
    "color": "var(--amber)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Jordan's 69: the night he went off against Cleveland — in overtime",
    "detail": "Michael Jordan poured in a then career-best 69 points in the Chicago Bulls' 117-113 overtime win over the Cleveland Cavaliers on February 27, 1990. He shot 23-of-37 from the field and hit 21 of 23 free throws. Chicago won the game in overtime.",
    "statChip": { "cls": "up", "text": "69 PTS" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "03-02",
    "year": 1962,
    "color": "var(--amber)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Wilt scores 100. Nobody has come close since.",
    "detail": "Wilt Chamberlain scored 100 points for the Philadelphia Warriors against the New York Knicks in Hershey, Pennsylvania on March 2, 1962. He shot 36-of-63 from the field and 28-of-32 from the free-throw line. The record has stood for over 60 years.",
    "statChip": { "cls": "up", "text": "100 PTS" },
    "players": ["Wilt Chamberlain"]
  },
  {
    "date_mmdd": "03-04",
    "year": 1987,
    "color": "var(--lime)",
    "tag": "RECORD",
    "tagIcon": "flame",
    "headline": "Jordan scores 61 against Detroit — and Chicago still loses",
    "detail": "Michael Jordan scored 61 points against the Detroit Pistons on March 4, 1987, in a losing effort. It was one of the highest single-game totals in Bulls history and showcased Jordan's dominance even without adequate supporting cast around him.",
    "statChip": { "cls": "up", "text": "61 PTS" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "03-18",
    "year": 1995,
    "color": "var(--coral)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "Michael Jordan returns. 45 on the scoreboard. The NBA woke up.",
    "detail": "Michael Jordan ended his 17-month retirement on March 19, 1995, wearing No. 45 for the Chicago Bulls. He scored 19 points in a loss to the Indiana Pacers in his first game back. Days later he dropped 55 on the Knicks at Madison Square Garden.",
    "statChip": { "cls": "up", "text": "17 MONTHS" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "03-28",
    "year": 1990,
    "color": "var(--lime)",
    "tag": "RECORD",
    "tagIcon": "flame",
    "headline": "Jordan's career-high: 69 points in overtime against the Cavs",
    "detail": "Michael Jordan poured in a career-best 69 points in the Chicago Bulls' 117-113 overtime win over the Cleveland Cavaliers on March 28, 1990. He shot 23-of-37 from the field and went 21-of-23 from the line in one of the great individual performances in NBA history.",
    "statChip": { "cls": "up", "text": "69 PTS" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "04-05",
    "year": 1987,
    "color": "var(--amber)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Michael Jordan wins his first NBA scoring title",
    "detail": "Michael Jordan of the Chicago Bulls clinched his first NBA scoring title on April 5, 1987, finishing the season with 37.1 points per game — the highest average in the league since Wilt Chamberlain's 44.8 in 1962. Jordan would go on to win seven more.",
    "statChip": { "cls": "up", "text": "37.1 PPG" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "04-07",
    "year": 1989,
    "color": "var(--blue)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Stockton becomes the first player with back-to-back 1,000-assist seasons",
    "detail": "John Stockton of the Utah Jazz became the first player in NBA history to record 1,000 assists in back-to-back seasons on April 7, 1989. He finished with 1,118 assists that year, one of five times he would exceed 1,000 in a season.",
    "statChip": { "cls": "up", "text": "1,000+ AST" },
    "players": ["John Stockton"]
  },
  {
    "date_mmdd": "04-13",
    "year": 1986,
    "color": "var(--coral)",
    "tag": "DYNASTY",
    "tagIcon": "crown",
    "headline": "Celtics go 40-1 at home — the greatest home season in NBA history",
    "detail": "The Boston Celtics wrapped up the best home season in NBA history on April 13, 1986, finishing 40-1 at Boston Garden. That Celtics team, led by Larry Bird, Kevin McHale, and Robert Parish, went on to win the NBA championship.",
    "statChip": { "cls": "up", "text": "40-1 HOME" },
    "players": ["Larry Bird", "Kevin McHale"]
  },
  {
    "date_mmdd": "05-01",
    "year": 1987,
    "color": "var(--lime)",
    "tag": "PLAYOFFS",
    "tagIcon": "flame",
    "headline": "Jordan drops 50 then 55 on Cleveland in back-to-back playoff games",
    "detail": "Michael Jordan scored 50 points in Game 1 of the 1987 playoffs against the Cleveland Cavaliers, then came back with 55 in Game 2 on May 1, 1987 — becoming the first player to score 50+ in consecutive playoff games. The Bulls won the series in five.",
    "statChip": { "cls": "up", "text": "50-55 PTS" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "05-07",
    "year": 1989,
    "color": "var(--lime)",
    "tag": "PLAYOFFS",
    "tagIcon": "zap",
    "headline": "The Shot. Jordan over Ehlo. Cleveland's heart breaks.",
    "detail": "Michael Jordan hit a double-clutch jumper over Craig Ehlo at the buzzer on May 7, 1989, eliminating the Cleveland Cavaliers in Game 5 of the first round. Jordan finished with 44 points. The image of him pumping his fist mid-air became one of sports' most iconic photographs.",
    "statChip": { "cls": "up", "text": "44 PTS" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "05-08",
    "year": 1970,
    "color": "var(--amber)",
    "tag": "DYNASTY",
    "tagIcon": "crown",
    "headline": "Willis Reed limps out and the Garden loses its mind",
    "detail": "Playing through a torn thigh muscle, Willis Reed walked onto the court for Game 7 of the NBA Finals against the Lakers at Madison Square Garden. He scored the Knicks' first two baskets, inspired the crowd, and Walt Frazier took it from there with 36 points and 19 assists. Final score: Knicks 113, Lakers 99 — New York's first NBA championship.",
    "statChip": { "cls": "up", "text": "113-99" },
    "players": ["Willis Reed", "Walt Frazier"]
  },
  {
    "date_mmdd": "05-08",
    "year": 2021,
    "color": "var(--lime)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Westbrook ties Robertson's all-time triple-double record",
    "detail": "Russell Westbrook recorded his 181st career triple-double on May 8, 2021, tying Oscar Robertson's record that had stood since 1974. He finished with 33 points, 19 rebounds, and 15 assists, then hit the go-ahead free throws and a game-clinching block in overtime to seal the Wizards win.",
    "statChip": { "cls": "up", "text": "181 TDs" },
    "players": ["Russell Westbrook"]
  },
  {
    "date_mmdd": "05-08",
    "year": 1999,
    "color": "var(--blue)",
    "tag": "PLAYOFFS",
    "tagIcon": "trophy",
    "headline": "The 1999 NBA Playoffs tip off — a lockout-shortened season begins",
    "detail": "The 1999 NBA Playoffs began on May 8, 1999, following a lockout-shortened 50-game regular season. The San Antonio Spurs, led by Tim Duncan, would go on to win the championship — their first title — defeating the New York Knicks in five games.",
    "statChip": { "cls": "up", "text": "1ST TITLE" },
    "players": ["Tim Duncan", "David Robinson"]
  },

  {
    "date_mmdd": "05-09",
    "year": 1970,
    "color": "var(--blue)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "Willis Reed named Finals MVP after inspiring the Knicks to their first title",
    "detail": "One day after his legendary tunnel walk, Willis Reed was named NBA Finals MVP on May 9, 1970. Reed had already won the regular season MVP and All-Star Game MVP that same year, making him one of the few players to win all three in a single season.",
    "statChip": { "cls": "up", "text": "TRIPLE MVP" },
    "players": ["Willis Reed"]
  },
  {
    "date_mmdd": "05-25",
    "year": 1987,
    "color": "var(--amber)",
    "tag": "PLAYOFFS",
    "tagIcon": "crown",
    "headline": "Magic's baby skyhook ends Game 4 and silences the Celtics",
    "detail": "Magic Johnson hit a running hook shot over Kevin McHale and Robert Parish with two seconds left on June 9, 1987, lifting the Lakers over the Celtics in Game 4 of the NBA Finals. Magic finished with 29 points, 8 assists, and 8 rebounds. The Lakers went on to win the championship.",
    "statChip": { "cls": "up", "text": "107-106" },
    "players": ["Magic Johnson"]
  },
  {
    "date_mmdd": "06-09",
    "year": 1987,
    "color": "var(--amber)",
    "tag": "PLAYOFFS",
    "tagIcon": "crown",
    "headline": "Magic's baby skyhook beats the Celtics in Game 4",
    "detail": "Magic Johnson hit a running hook shot over Kevin McHale and Robert Parish with two seconds left on June 9, 1987, giving the Lakers a 107-106 win over the Celtics in Game 4 of the NBA Finals. It remains one of the most clutch shots in Finals history.",
    "statChip": { "cls": "up", "text": "107-106" },
    "players": ["Magic Johnson"]
  },
  {
    "date_mmdd": "06-11",
    "year": 1997,
    "color": "var(--lime)",
    "tag": "PLAYOFFS",
    "tagIcon": "flame",
    "headline": "The Flu Game. Jordan drops 38 with food poisoning. Bulls win.",
    "detail": "Michael Jordan scored 38 points in Game 5 of the 1997 NBA Finals against the Utah Jazz on June 11, 1997, despite suffering from severe flu-like symptoms the night before. He hit the go-ahead three-pointer late in the fourth quarter. The Bulls won 90-88 and took a 3-2 series lead.",
    "statChip": { "cls": "up", "text": "38 PTS" },
    "players": ["Michael Jordan"]
  },
  {
    "date_mmdd": "06-12",
    "year": 1998,
    "color": "var(--lime)",
    "tag": "PLAYOFFS",
    "tagIcon": "crown",
    "headline": "The Last Shot. Jordan steals, shoots, wins. Chicago's sixth title.",
    "detail": "Michael Jordan stripped the ball from Karl Malone with 18.9 seconds left, then hit a pull-up jumper over Bryon Russell with 5.2 seconds remaining on June 14, 1998, to give the Bulls an 87-86 win over the Jazz in Game 6 of the NBA Finals — Chicago's sixth championship in eight years.",
    "statChip": { "cls": "up", "text": "6TH TITLE" },
    "players": ["Michael Jordan", "Scottie Pippen"]
  },
  {
    "date_mmdd": "06-13",
    "year": 2013,
    "color": "var(--coral)",
    "tag": "PLAYOFFS",
    "tagIcon": "star",
    "headline": "Ray Allen's corner three forces overtime. Miami stays alive.",
    "detail": "Ray Allen hit a corner three-pointer with 5.2 seconds left to tie Game 6 of the 2013 NBA Finals at 95, forcing overtime on June 18, 2013. The Miami Heat won in OT 103-100, then closed out the San Antonio Spurs in Game 7 for their second consecutive championship.",
    "statChip": { "cls": "up", "text": "103-100 OT" },
    "players": ["Ray Allen", "LeBron James"]
  },
  {
    "date_mmdd": "06-16",
    "year": 1996,
    "color": "var(--lime)",
    "tag": "DYNASTY",
    "tagIcon": "crown",
    "headline": "Bulls win their fourth title — and complete a 72-win season",
    "detail": "The Chicago Bulls defeated the Seattle SuperSonics in Game 6 of the 1996 NBA Finals on June 16, 1996, to complete a season that began with a 72-10 regular season record — the best in NBA history at the time. Michael Jordan won his fourth championship and Finals MVP.",
    "statChip": { "cls": "up", "text": "72-10 RSN" },
    "players": ["Michael Jordan", "Scottie Pippen", "Dennis Rodman"]
  },
  {
    "date_mmdd": "06-19",
    "year": 2016,
    "color": "var(--coral)",
    "tag": "COMEBACK",
    "tagIcon": "trending-up",
    "headline": "LeBron's block. Kyrie's shot. Cleveland ends a 52-year drought.",
    "detail": "LeBron James made a chase-down block on Andre Iguodala with 1:50 left, and Kyrie Irving hit a three-pointer over Steph Curry with 53 seconds remaining in Game 7 on June 19, 2016. The Cavaliers won 93-89, completing a 3-1 series comeback against the Warriors — the first major North American sports team to do it in a title series.",
    "statChip": { "cls": "up", "text": "3-1 COMEBACK" },
    "players": ["LeBron James", "Kyrie Irving"]
  },
  {
    "date_mmdd": "07-01",
    "year": 2010,
    "color": "var(--coral)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "LeBron James enters free agency. The whole NBA holds its breath.",
    "detail": "LeBron James officially became a free agent on July 1, 2010, triggering the most scrutinized free agency period in NBA history. Nine days later he would announce his decision to join the Miami Heat in a live television special that changed how player movement was covered forever.",
    "statChip": { "cls": "up", "text": "FREE AGENT" },
    "players": ["LeBron James"]
  },
  {
    "date_mmdd": "07-09",
    "year": 2003,
    "color": "var(--blue)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "LeBron James signed by the Cleveland Cavaliers as the #1 pick",
    "detail": "LeBron James signed his rookie contract with the Cleveland Cavaliers on July 9, 2003, after being selected first overall in the 2003 NBA Draft. The 18-year-old from Akron, Ohio, was already being called 'The Chosen One' and had been on the cover of Sports Illustrated as a high school junior.",
    "statChip": { "cls": "up", "text": "#1 PICK" },
    "players": ["LeBron James"]
  },
  {
    "date_mmdd": "08-18",
    "year": 1992,
    "color": "var(--amber)",
    "tag": "MILESTONE",
    "tagIcon": "trophy",
    "headline": "The Dream Team wins gold. Basketball was never the same globally.",
    "detail": "The United States Dream Team won the gold medal at the 1992 Barcelona Olympics on August 8, 1992, defeating Croatia 117-85 in the final. The team — featuring Michael Jordan, Magic Johnson, Larry Bird, Charles Barkley, and Patrick Ewing — averaged 117 points per game and won every game by at least 32 points.",
    "statChip": { "cls": "up", "text": "GOLD MEDAL" },
    "players": ["Michael Jordan", "Magic Johnson", "Larry Bird"]
  },
  {
    "date_mmdd": "09-12",
    "year": 1962,
    "color": "var(--blue)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "Wilt Chamberlain traded to the 76ers — a seismic franchise shift",
    "detail": "Wilt Chamberlain was traded from the San Francisco Warriors to the Philadelphia 76ers on September 12, 1962, in one of the most consequential trades in NBA history. He would lead Philadelphia to the 1967 NBA championship, ending the Boston Celtics' run of eight consecutive titles.",
    "statChip": { "cls": "up", "text": "TRADED" },
    "players": ["Wilt Chamberlain"]
  },
  {
    "date_mmdd": "10-12",
    "year": 1979,
    "color": "var(--amber)",
    "tag": "DEBUT",
    "tagIcon": "star",
    "headline": "Magic Johnson's first NBA game: 26 points, 16 rebounds as a rookie",
    "detail": "Magic Johnson made his NBA debut on October 12, 1979, scoring 26 points and grabbing 16 rebounds in a 103-102 Los Angeles Lakers win over the San Diego Clippers. The 20-year-old point guard had just left Michigan State after one season as a national champion.",
    "statChip": { "cls": "up", "text": "26 PTS, 16 REB" },
    "players": ["Magic Johnson"]
  },
  {
    "date_mmdd": "10-18",
    "year": 2003,
    "color": "var(--coral)",
    "tag": "DEBUT",
    "tagIcon": "star",
    "headline": "LeBron James debuts: 25 points, 9 assists, 6 rebounds",
    "detail": "LeBron James scored 25 points with 9 assists and 6 rebounds in his NBA debut on October 29, 2003, in a Cleveland Cavaliers win over the Sacramento Kings. He became the third player in NBA history to score 25+ points in his debut, joining Kareem Abdul-Jabbar and Shaquille O'Neal.",
    "statChip": { "cls": "up", "text": "25 PTS DEBUT" },
    "players": ["LeBron James"]
  },
  {
    "date_mmdd": "11-12",
    "year": 2010,
    "color": "var(--blue)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Kevin Love posts 31 points and 31 rebounds — the NBA's first 30-30 game in 28 years",
    "detail": "Kevin Love of the Minnesota Timberwolves scored 31 points and grabbed 31 rebounds against the New York Knicks on November 12, 2010 — the first 30-30 game in the NBA since Kareem Abdul-Jabbar in 1982. Love did it despite fouling out with 2:17 remaining.",
    "statChip": { "cls": "up", "text": "31 PTS / 31 REB" },
    "players": ["Kevin Love"]
  },
  {
    "date_mmdd": "11-17",
    "year": 1979,
    "color": "var(--amber)",
    "tag": "MILESTONE",
    "tagIcon": "star",
    "headline": "The NBA introduces the three-point line for the first time",
    "detail": "The NBA introduced the three-point line for the 1979-80 season, with the first three-pointer in league history made by Chris Ford of the Boston Celtics on October 12, 1979. The rule — borrowed from the ABA — transformed NBA strategy over the following four decades.",
    "statChip": { "cls": "up", "text": "FIRST 3PT" },
    "players": ["Chris Ford"]
  },
  {
    "date_mmdd": "11-20",
    "year": 1997,
    "color": "var(--blue)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "A.C. Green plays in his 907th straight game, breaking the iron man record",
    "detail": "A.C. Green of the Dallas Mavericks played in his 907th consecutive game on November 20, 1997, breaking the NBA record for consecutive games played set by Randy Smith. Green would eventually extend the streak to 1,192 games — a record that may never be broken.",
    "statChip": { "cls": "up", "text": "907 STRAIGHT" },
    "players": ["A.C. Green"]
  },
  {
    "date_mmdd": "12-13",
    "year": 1983,
    "color": "var(--coral)",
    "tag": "RECORD",
    "tagIcon": "flame",
    "headline": "Pistons vs Nuggets: the highest-scoring game in NBA history — 370 points",
    "detail": "The Detroit Pistons defeated the Denver Nuggets 186-184 in triple overtime on December 13, 1983 — the highest-scoring game in NBA history with 370 combined points. Six players scored 40+ points, including Detroit's Isiah Thomas (47) and Kiki Vandeweghe's 51 for Denver.",
    "statChip": { "cls": "up", "text": "370 PTS" },
    "players": ["Isiah Thomas", "Kiki Vandeweghe"]
  },
  {
    "date_mmdd": "12-20",
    "year": 2005,
    "color": "var(--lime)",
    "tag": "RECORD",
    "tagIcon": "flame",
    "headline": "Kobe scores 62 in three quarters — then sits the fourth",
    "detail": "Kobe Bryant scored 62 points in just three quarters against the Dallas Mavericks on December 20, 2005, before sitting out the fourth quarter of a blowout win. Dallas's Dirk Nowitzki, one of the greatest scorers ever, finished with 26. The Mavs had no answer.",
    "statChip": { "cls": "up", "text": "62 PTS/3 QTR" },
    "players": ["Kobe Bryant"]
  },
  {
    "date_mmdd": "12-30",
    "year": 1990,
    "color": "var(--blue)",
    "tag": "RECORD",
    "tagIcon": "trending-up",
    "headline": "Scott Skiles dishes 30 assists — an NBA record that has stood 35 years",
    "detail": "Scott Skiles of the Orlando Magic handed out 30 assists in a 155-116 win over the Denver Nuggets on December 30, 1990 — the most assists by any player in a single NBA game. The record has never been broken. Skiles was stuck on 29 for most of the fourth quarter before recording the final dime with a minute left.",
    "statChip": { "cls": "up", "text": "30 AST" },
    "players": ["Scott Skiles"]
  }
];
